// checkm if js is working correctly
//console.log("Helllo quiz");

// Get all of the questions and the text in them
const question =document.getElementById("question");
const choices = Array.from(document.getElementsByClassName("choiceText"));
//reference for Loader, Quiz & Quiz Info
const loader = document.getElementById('loader');
const game = document.getElementById('game');
const progText = document.getElementById('progText');
const scoreText = document.getElementById('score');
const barFill = document.getElementById('barFill');
// Creation of global variables
let currentQuestion ={};
let gettingAnswers= false;
let score = 0;
let qCounter = 0;
let newQuestions = [];
//Creates array to store questions and fetches data from API
let questions = [];

// API generated by https://opentdb.com/ on 14/03/2026
fetch("https://opentdb.com/api.php?amount=20&category=18&difficulty=medium&type=multiple").then(res => {
    return res.json();
}).then(loadedQs => {
    console.log(loadedQs);
    //converts API data to differemt format
   questions = loadedQs.results.map( loadedQ => {
        const formattedQ ={ 
            question : loadedQ.question
        };

        // gets inc/cor answers and puts in random posotion
        const ansChoices = [...loadedQ.incorrect_answers];
        formattedQ.answer = Math.floor(Math.random()*4)+1;
        ansChoices.splice(formattedQ.answer -1, 0, loadedQ.correct_answer);

        ansChoices.forEach((choice, index) => {
            formattedQ["choice" + (index+1)] = choice;
        })
        return formattedQ;
    });
    startQuiz();
}).catch( err => {
    //errors out if out if trying to get invalid data
    console.error(err);
    
});
const CorrectScore = 5;           
const NumberOfQuestions = 10; //Maximum of 20 from current API Setiings

// Loads questions into array and resets counter and score
startQuiz = () => {
    // Initializing variables to 0
    qCounter = 0;
    score = 0;
    // CRITICAL POINT: putting hard coded qustions into new array
    newQuestions = [...questions];
    getNewQuestions();
    //Adds loading screen to prevent display of placeholder text
    game.classList.remove("hidden");
    loader.classList.add("hidden");
};

//Increments question counter and randomizes the next question and answers
getNewQuestions = () =>{

    // Checks if there's anymore questions to show
    if(newQuestions.length === 0 || qCounter >= NumberOfQuestions){
        //stores score to local storage
        localStorage.setItem('newestScore', score);
        // Go to the complete quiz page
        return window.location.assign("/EndQuiz.html");
    }
    qCounter++;
    //update quiz info text and progress bar
    progText.innerText = `Quetsion ${qCounter}/${NumberOfQuestions}`;
    barFill.style.width = `${(qCounter/NumberOfQuestions) * 100}%`; 

    const qIndex = Math.floor(Math.random() * newQuestions.length);
    currentQuestion = newQuestions[qIndex];
    question.innerText = currentQuestion.question;

    choices.forEach( choice => {
        const number = choice.dataset['number'];
        choice.innerText = currentQuestion['choice' + number];
    });
    // removes the question that was just used from the array
    newQuestions.splice(qIndex, 1);

    gettingAnswers = true;

};
// checks if selected answer is correct and calls getNewQuestions
choices.forEach(choice =>{
    choice.addEventListener("click", e => {
        if(!gettingAnswers) return;

        gettingAnswers = false;

        // creation of local variables
        const selectedAns = e.target;
        const selectedAnswer = selectedAns.dataset["number"];
        // Ternary operator, if selected answer is correct applies correct class, if not applies incorect class
        const applyClass = selectedAnswer == currentQuestion.answer ? "correct" : "incorrect";
        selectedAns.parentElement.classList.add(applyClass)
        //calls addScore function if coorect answer is selected, increasing it by 'CorrectScore'
        if(applyClass === 'correct'){
            addScore(CorrectScore);
        }

        // removes correct/incorrect class and gets next question after pause
        setTimeout(() => {
            selectedAns.parentElement.classList.remove(applyClass)
            getNewQuestions();
        },1000);

    });
});
//Increases score for every correct question and updates html
addScore = num => {
    score +=num;
    scoreText.innerText = score;
}
